[package]
name = "swiss_cheese"
version = "0.1.4"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "swiss_cheese"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.17.2"
numpy = "0.28.0"
pyo3 = "0.28.0"
rand = "0.10.1"
threadpool = "1.8.1"
